/**
 * findingsReportComposer — the SINGLE, pure, deterministic composer for the
 * metaMe Invariant Research Lab Findings Report. Used by BOTH the live-draft
 * client tab (ExperimentReportTab) and the canonical server regeneration
 * (services/research/reportComposition.ts) so there is exactly ONE composition
 * of record — no drift, and no LLM latency (the canonical regenerate previously
 * called a sovereign model and 504'd at the ~30s gateway envelope).
 *
 * Composition obeys the platform's own laws (dogfooding EXP-002): experiments
 * are emitted in canonical EXPERIMENT_REGISTRY order grouped under their series
 * (sequential narrative law), and the introduction is generated from the same
 * registry + record (global coherence) — a single ordered document, never a
 * narrated head with an appended tail. An experiment with no runs yet but an
 * authored body (e.g. EXP-005) appears in its correct slot as publication
 * pending; a published run outside the registry is preserved under a labelled
 * "Further experiments" block (registry drives ORDER, never suppression).
 *
 * Pure: no React, no DB, no crypto, no provider calls — safe to import from
 * both a client component and a server route.
 */

import { EXPERIMENT_REGISTRY, SERIES_REGISTRY, type ResearchExperiment } from "@/types/research";

/** One canonical run, provider-agnostic (both call sites map their row to this). */
export interface ReportRun {
  provider: string;
  model: string;
  aggregates: Record<string, unknown>;
  contentHash: string;
  receiptStatus?: string | null;
  /** ISO timestamp. */
  createdAt: string;
}

function aggLine(agg: Record<string, unknown>): string {
  return Object.entries(agg ?? {})
    .filter(([k]) => k !== "note")
    .map(([k, v]) => `${k}: ${typeof v === "number" ? Math.round(v * 1000) / 1000 : String(v)}`)
    .join(" · ");
}

function runsTable(rows: ReportRun[]): string {
  if (rows.length === 0) return "_No canonical runs published yet for this experiment._\n";
  const lines = [
    "| Published | Provider / model | Aggregates | Content commitment (sha256) | DVN |",
    "|---|---|---|---|---|",
  ];
  for (const r of rows) {
    lines.push(
      `| ${new Date(r.createdAt).toISOString().slice(0, 10)} | ${r.provider} / ${r.model} | ${aggLine(r.aggregates) || "—"} | \`${r.contentHash.slice(0, 16)}…\` | ${r.receiptStatus ?? "local"} |`,
    );
  }
  return lines.join("\n") + "\n";
}

/**
 * Objective, data-driven EXP-006 → EXP-006A narrative BODY (no heading, no runs
 * table — the composition loop supplies both). The exact-set F1 is a LOWER BOUND
 * distorted by abstraction mismatch, not a competence score.
 */
function exp006Body(rows: ReportRun[]): string {
  const pctf = (v: number | null) => (v === null ? "—" : `${Math.round(v * 100)}%`);
  const framing = `**Aim.** Move from *outcome* evaluation to *mechanism* evaluation: can the invariant projection engine identify the governing invariant set for an intent **independently of a human-authored reference** — i.e. did it select the right constitutional substrate before reasoning began?

**Method (Stage A).** For each intent in an independently-generated reference set (CIRS), the sovereign, invariant-aware router predicts the projection; it is scored against the *blind* reference; every disagreement is classified as an Invariant Delta. The reference is generated by a different reasoning stage/provider than the predictor, so the deltas are real cross-model disagreements, not self-agreement.`;

  const successor = `**EXP-006A — the successor metric.** Topology / abstraction-aware scoring reclassifies each disagreement as *vocabulary* (normalisation), *abstraction* (predicted subsumes a reference item — same family, different level), *omission* (a genuine gap), or *redundant*. The subsumption signal is **graph-truth first**: it reads the invariant graph's \`specializes\`/\`generalizes\` edges (built by the Discovery Engine's Compare + parent-linking) and falls back to an embedding proxy only where a label is not yet a registry node — reporting the two separately so they are never conflated. Projection Fidelity becomes a composite (structural + causal coverage + minimality), so a low lexical F1 can coexist with high causal agreement.

**Engine roles EXP-006 clarified.** The **Invariant Resolution Engine** projects an intent *down* to a minimal invariant set; the **Discovery Engine's Compare** compresses many sub-domain sets *up* into earned higher-order invariants; **EXP-006A** scores a projection *against* that same graph. They are inverse operations over one invariant graph — and EXP-006 plateaued precisely because the Discovery Engine had outgrown a name-matching metric.

**For anyone running EXP-006:** publish the lexical baseline, frame it as *lexical agreement with a known abstraction ceiling* (not "the engine scores 0.4X"), then **follow on to EXP-006A** for the causal-agreement metric.`;

  if (rows.length === 0) {
    return `${framing}\n\n**Status.** Run complete; canonical publication pending. Superseded as the *fidelity metric* by **EXP-006A** (topology / abstraction-aware).\n\n${successor}`;
  }
  const latest = rows.slice().sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime())[0];
  const agg = latest.aggregates ?? {};
  const p = typeof agg.meanPrecision === "number" ? (agg.meanPrecision as number) : null;
  const r = typeof agg.meanRecall === "number" ? (agg.meanRecall as number) : null;
  const f1 = p !== null && r !== null && p + r > 0 ? (2 * p * r) / (p + r) : null;
  const deltas = typeof agg.deltaCount === "number" ? (agg.deltaCount as number) : null;

  return `${framing}

**Measured (latest canonical run, ${new Date(latest.createdAt).toISOString().slice(0, 10)}, ${latest.provider} / ${latest.model}).** Exact-set *lexical* fidelity: precision ${pctf(p)} · recall ${pctf(r)} · F1 ${pctf(f1)}${deltas !== null ? ` · ${deltas} Invariant Deltas classified` : ""}.

**Finding — read objectively, this F1 is a lower bound, not a competence score.** The exact-set metric measures *lexical* agreement, and two facts make the raw number a distorted floor:
1. The sovereign router projects invariants **one abstraction level higher** than the flat reference — e.g. for an authenticated-delegation intent it returns \`authentication · delegation · security\`, which *subsume* the reference's \`token-validation · scope-limitation · secure-access\`. Exact scoring reads that as zero overlap; it is an abstraction mismatch, not a projection failure.
2. The semantic-retrieval baseline that looks competitive draws from the *reference's own vocabulary* (it retrieves labels resembling the answer key), while the sovereign router projects independently. Different tasks; the comparison flatters retrieval.

Invariant selection therefore cannot be evaluated as flat set-overlap. **EXP-006 is frozen here as the last lexical-fidelity record** — it has done its job: it established that the scientific question is *did the engine select the correct invariant family, at the correct abstraction level, with a minimal sufficient set?*

${successor}`;
}

// Authored narrative bodies (aim/methodology/execution/findings), keyed by id.
// Each returns the BODY only — the loop supplies the heading + live runs table.
const AUTHORED_BODIES: Record<string, (rows: ReportRun[]) => string> = {
  "EXP-001": () => `**Aim.** Render one 18-invariant constitutional collection into four text
artifacts (canonical article, technical report, narrative story,
infographic spec) and test whether an independent judge can recover the same
substantive answers from every rendering — and whether the artifacts refuse
to assert what the collection does not contain.

**Methodology.** 15 questions per artifact, including 3 adversarial
"hallucination probes" whose correct answer is NOT DERIVABLE. An independent
judge model (different provider from the author) scores consistency,
explainability (citation-traceability to invariant markers), hallucination,
and coherence. Machine verdicts are then human-adjudicated; adjudication can
only lower scores or dissolve machine flags with recorded reasons.

**Execution (run 1, 2026-07-04).** Judge: venice/llama-3.3-70b, temperature 0.

**Findings (adjudicated).** Consistency 1.83 (target ≥ 1.8); explainability
1.95 (≥ 1.6); artifact-attributable hallucinations 0; coherence 2.0;
**constitutional restraint 15/15 (100%)** — every probe across every document
correctly returned NOT DERIVABLE. The artifacts did not merely preserve what
the collection says; they refused to invent what it does not. Both
machine-raised hallucination flags dissolved under adjudication (one judge
false-positive, one judge retrieval failure — the latter scored honestly
against the run's consistency rather than the artifacts).`,

  "EXP-002": () => `**Aim.** Compose one brief from the invariant substrate — semantic
invariants distributed across segments, a 7-invariant style continuity block
shared identically, a 5-beat narrative arc mapped sequentially — and test
whether coherence survives four independent 12-second video generations
stitched into one 48-second film.

**Methodology.** The brief is machine-composed by per-class composition laws
(distributive × global × sequential) and validated pre-render by a
Constitutional Coherence Engine scoring semantic, style, and narrative
dimensions. Generation runs on a production video provider; segments stitch
in the recorded play order. A **sequencing control arm** re-stitches the
identical clips in reversed order.

**Execution (run 2, 2026-07-05).** Provider: openai/sora-2, 4×12s.
(Run 1, 2026-07-04, validated the composition+coherence half and caught a
real narrative-mapping defect pre-render — fixed same day.)

**Findings.**
- Complete continuity of narrative, protagonist, settings, and constitutional
  context across all four independently generated segments (operator
  evaluation + frame-level review; formal independent-evaluator pass open).
- The recurring constitutional symbol persisted across three segments in
  three different material implementations (necklace, lapel pin, wall
  banner) — and was correctly absent from the one segment whose narrative
  context didn't call for it. Motif persistence modulated by narrative
  appropriateness: the style and narrative fields solved simultaneously.
- Character persistence held at the class level but not the instance level
  (facial phenotype varied between segments) — a measured granularity
  ceiling of prose-based identity continuity, now a ratified backlog item.
- **Control arm:** the reversed cut is distinctly less coherent while world,
  style, and semantic content stay intact — the dissociation signature of a
  pure sequencing failure. Two refinements were ratified from it: temporal
  correctness is *graded, not boolean* ("sequence is scored, not validated" —
  the designed order is a coherence maximum over the space of orderings),
  and local pairwise coherence survives a global order violation. A
  follow-up (EXP-002b) maps the coherence field's shape via adjacent-swap
  perturbations at zero generation cost.`,

  "EXP-003": () => `**Aim.** Quantify the cost of *not* having validated knowledge: five fixed
constitutional-design tasks answered twice by the same model at temperature
0 — once cold, once initialized with the 18-invariant collection.

**Methodology.** Per-task token accounting (input + output) plus an
independent judge decomposing each answer into claims scored consistent /
contradicting / outside the collection, and citation counting against
invariant markers. The efficiency claim requires the initialized arm to be
cheaper AND more grounded, not merely shorter.

**Execution (run 1, 2026-07-04).** Model: venice/llama-3.3-70b, both arms.

**Findings.** Initialized answers used **26.7% fewer tokens** with **100%
grounded claims** (zero contradictions of the collection) and dense
citations; cold answers were longer, uncited, and — most tellingly — one
cold answer **independently rediscovered a failure mode the collection
already encodes** (conflating standing with popularity, the platform's
ratified Law XII distinction) and got it wrong, while the initialized arm
avoided it by construction. Pre-paid reasoning eliminated the rediscovery.`,

  "EXP-004": (rows) => `**Aim.** Test whether invariant-grounded constitutional operation **survives on
a non-frontier, self-hostable (open-weight) provider alone** — quality may
degrade, constitutional operation shall not. Sovereignty is a first-class
platform claim: a citizen's reasoning must not depend on a single vendor.

**Methodology.** The same grounded battery runs through the sovereign-floored
model router (\`callSovereign\`) and is judged for grounded operation against a
frontier arm at equal grounding; provider and model are recorded per arm and
never merged. A rehearsal/frontier-fallback arm is recorded transparently as
such when a self-hosted provider is unavailable.

**Findings.** Across the published runs, constitutional operation held at the
**S2 (substitutable) sovereignty rung** with high grounded-claim rates and
zero-to-low contradictions${
    rows.length > 0 ? ` (see the ${rows.length} canonical run${rows.length > 1 ? "s" : ""} below)` : ""
  }. Where a run shows lower groundedness (and non-zero contradictions), it is
retained honestly rather than dropped — that is the failure signature that
defines the floor the claim is measured against, not an embarrassment to hide.`,

  "EXP-005": () => `**Aim.** Isolate **provider choice** as a measured sovereignty-bundle
component: the same constitutional battery hands across *interchangeable*
providers mid-run (cross-provider judged) and constitutional operation
survives the switch — S2 *exercised*, not merely available. Where EXP-004
asks "does it hold on a sovereign provider?", EXP-005 asks "is the outcome
invariant to provider choice?"

**Methodology.** The same grounded task runs across ≥2 interchangeable
providers at identical grounding; per-arm provider/model is recorded and
never merged. Each task lands in one honest class — completed,
constitutionally_failed (the only switch-integrity failure), provider_unavailable,
timed_out, or judge_failed — and the run reports two independent axes:
constitutional portability (does valid operation survive substitution?) and
operational viability (can each provider fill its role within the runtime
envelope?).

**Status.** Run complete; canonical publication via the Results record. Where
a run table appears below it renders live from that record; where publication
is still pending this section says so rather than drop the experiment from the
series — provider choice is part of the sovereignty claim and belongs in
sequence between EXP-004 and the Invariant Intelligence series.`,

  "EXP-006": exp006Body,
};

/** Framed auto-section for an experiment with published runs but no authored prose. */
function framedBody(exp: ResearchExperiment): string {
  return `**Aim.** ${exp.hypothesis}

_Auto-summarised from the experiment registry; the full protocol lives in the repository (\`${exp.protocolRef}\`)._`;
}

/** Section title — EXP-006 signals its EXP-006A succession in the heading. */
function titleFor(exp: ResearchExperiment): string {
  return exp.id === "EXP-006" ? `EXP-006 → EXP-006A — ${exp.family}` : `${exp.id} — ${exp.family}`;
}

export interface FindingsReportInput {
  /** Published canonical runs grouped by experiment id. */
  runsByExp: Record<string, ReportRun[]>;
  /** Composition timestamp (the "Report generated" date). */
  now: Date;
}

/** Compose the whole Findings Report markdown deterministically. */
export function composeFindingsReport({ runsByExp, now }: FindingsReportInput): string {
  const byExp = (id: string): ReportRun[] => runsByExp[id] ?? [];
  const runCount = (id: string) => byExp(id).length;
  const memberStatus = (id: string) => {
    const c = runCount(id);
    return c > 0 ? `**validated** (${c} canonical run${c > 1 ? "s" : ""})` : "run complete; canonical publication pending";
  };

  const allRuns = Object.values(runsByExp).flat();
  const latestRunDate =
    allRuns.length > 0
      ? new Date(Math.max(...allRuns.map((r) => new Date(r.createdAt).getTime()))).toISOString().slice(0, 10)
      : null;
  const distinctExpCount = Object.keys(runsByExp).filter((id) => (runsByExp[id]?.length ?? 0) > 0).length;
  const totalRuns = allRuns.length;

  // Sequential composition — one ordered spine (canonical registry order,
  // grouped by series). Included if authored OR has any published run.
  const included = EXPERIMENT_REGISTRY.filter((e) => AUTHORED_BODIES[e.id] || runCount(e.id) > 0);
  const seriesInOrder = SERIES_REGISTRY.filter((s) => included.some((e) => e.seriesId === s.id));

  let n = 0;
  const num = () => (n += 1);
  const introNo = num();
  const trustNo = num();

  const programmeMap = seriesInOrder
    .map((s) => {
      const members = included
        .filter((e) => e.seriesId === s.id)
        .map((e) => `  - **${e.id}** — ${e.family}: ${memberStatus(e.id)}`)
        .join("\n");
      return `**${s.name}.** ${s.claim}\n${members}`;
    })
    .join("\n\n");

  let lastSeries = "";
  const expSections = included
    .map((exp) => {
      let banner = "";
      if (exp.seriesId !== lastSeries) {
        lastSeries = exp.seriesId;
        const s = SERIES_REGISTRY.find((x) => x.id === exp.seriesId);
        if (s) banner = `---\n\n### ${s.name}\n*${s.claim}*\n\n`;
      }
      const body = AUTHORED_BODIES[exp.id] ? AUTHORED_BODIES[exp.id](byExp(exp.id)) : framedBody(exp);
      return `${banner}## ${num()}. ${titleFor(exp)}\n\n${body}\n\n**Canonical runs:**\n${runsTable(byExp(exp.id))}`;
    })
    .join("\n");

  // No-data-loss: published runs outside the pinned registry still appear.
  const registeredIds = new Set(EXPERIMENT_REGISTRY.map((e) => e.id));
  const orphanIds = Object.keys(runsByExp)
    .filter((id) => (runsByExp[id]?.length ?? 0) > 0 && !registeredIds.has(id))
    .sort();
  const orphanSections = orphanIds
    .map((id, i) => {
      const banner =
        i === 0
          ? "---\n\n### Further experiments\n*Published runs outside the pinned experiment registry — surfaced so no canonical record is dropped.*\n\n"
          : "";
      return `${banner}## ${num()}. ${id}\n\n**Aim.** _Not in the pinned registry; see the experiment's protocol in the repository._\n\n**Canonical runs:**\n${runsTable(byExp(id))}`;
    })
    .join("\n");

  const conclusionsNo = num();
  const limitationsNo = num();
  const inviteNo = num();

  return `# The metaMe Invariant Research Lab — Findings Report (Draft)

**Chrysalis Foundation / Invariant Intelligence · AigentZ platform**
**Status: CONFIDENTIAL DRAFT for strategic partners — not for publication or redistribution**
**Report generated: ${now.toISOString().slice(0, 10)} · Latest canonical run: ${latestRunDate ?? "none yet"} · ${totalRuns} published run${totalRuns === 1 ? "" : "s"} across ${distinctExpCount} experiment${distinctExpCount === 1 ? "" : "s"}**
*Composed sequentially by the platform's own narrative-sequencing + coherence composition laws (EXP-002): experiments appear in canonical series order and the introduction reflects the full record — this is a single ordered document, not a narrated head with an appended tail. Run tables render live from the canonical record.*

---

## ${introNo}. Introduction — what is being validated

The platform's core knowledge primitive is the **invariant**: a versioned,
provenance-bearing statement of validated knowledge (e.g. *"Authority follows
standing"*), stored in a graph, classified by an ontology, and composed by
per-class composition laws into experiences — articles, reports, stories,
video, agent behaviour. The claim under test is **reasoning compression**:
that a curated collection of validated invariants functions as compressed,
reusable expertise which survives transformation across modalities, survives
composition across time, and measurably reduces the cost of reasoning while
improving its fidelity.

The research programme is organised into **series**, each isolating a distinct
property of the invariant substrate. This report reflects the **full canonical
record to date** — every series with a published run, and every member
experiment in its canonical sequence (an experiment whose run is complete but
not yet published is shown in place as *publication pending*, never omitted):

${programmeMap}

Every run is a separate experiment instance — provider and model are recorded
with each result and cross-model rows are never merged.

## ${trustNo}. Trust model — why the numbers are auditable

Every published run stores its **exact results JSON** and a sha256 content
commitment over that exact text, anchored via a DVN-anchorable
(\`experiment_result_published\`) receipt on the platform's Decentralised
Verification Network pipeline. Verification is trustless and mechanical:
recompute sha256 over the stored text and compare with the anchored hash —
the platform's Results interface does this in-browser, taking no server
assertion on faith. The hashes in the data tables below are those
commitments.

${expSections}
${orphanSections ? orphanSections + "\n" : ""}---

## ${conclusionsNo}. Cross-cutting conclusions (current)

1. **One primitive, validated along orthogonal axes across several series.**
   Semantic fidelity across modalities (FVS), temporal fidelity across
   sequential composition (FVS), reasoning-cost reduction (FVS), constitutional
   operation under a sovereign provider and across interchangeable providers
   (Platform Sovereignty), and mechanism-level projection fidelity (Invariant
   Intelligence) — the same invariant substrate examined from independent
   directions, each a separate measurable property.
2. **Constitutional restraint is a distinct, measurable property.** Refusing
   to derive what the knowledge does not contain (15/15 probes in EXP-001) is
   separable from avoiding false assertions — and it is the property that
   makes invariant-grounded systems auditable.
3. **Composition is where both failures and validations live.** Every defect
   found by the series lived in an *interaction between fields* (a narrative
   beat lost in segment mapping; audio overrunning a segment boundary), never
   in a single component — and the validators built on that principle caught
   a real defect before a single frame was generated.
4. **Sequence is scored, not validated.** The reversed-order control (EXP-002)
   showed temporal coherence is a graded field over orderings with the designed
   sequence as its maximum — opening constrained resequencing (remix as an
   alternative coherent trajectory through the same invariant space) as a
   legitimate, scoreable operation. *This report is composed under that same
   law — its section order is the coherence maximum over the experiment set.*

## ${limitationsNo}. Limitations, stated plainly

- Single-model runs for the foundational legs (one OSS model for the text
  legs; one video provider) — those deltas are within-model; constants are not
  yet universals. Cross-model replication is the first scale-up step. (The
  sovereignty series already spans multiple providers by design.)
- The judge is a model; machine verdicts required human adjudication (both
  instructive, both recorded).
- EXP-002's formal independent-evaluator pass is open; current findings are
  operator-evaluated with frame evidence.
- The foundational collection was authored by the platform's own constitutional
  process — task-collection affinity is by design; cross-domain generalization
  is under active test (the Discovery Engine's domain-ladder + cross-domain
  comparison), not yet concluded.
- EXP-006's exact-set metric is a **lexical lower bound** with a known
  abstraction ceiling; its causal-agreement successor (EXP-006A) is the metric
  to read for projection competence.

## ${inviteNo}. What we're inviting partners to do

The next tier of rigor needs scale we intend to reach with partners: larger
task sets, multiple judge models, cross-domain collections, more permutation
coverage for the temporal-coherence field map (EXP-002b), and independent
replication of the initialization and sovereignty deltas. The full experiment
protocols, artifacts, and raw result records are available on request under the
same confidentiality.

---
*Draft report — composed deterministically from the canonical results record at
regeneration time. Sections are in canonical series/experiment order; the
introduction and data tables update automatically as runs are published.*
`;
}
