# QubeAgent Configuration

# Blockchain Configuration
web3_provider_url: https://mainnet.infura.io/v3/YOUR_PROJECT_ID
wallet_private_key: your_wallet_private_key_here
default_network: ethereum

# iQube Registry Configuration
iqube_registry_contract_address: '0x1234567890123456789012345678901234567890'
token_contract_address: '0x0987654321098765432109876543210987654321'

# Content Storage
ipfs_endpoint: '/ip4/127.0.0.1/tcp/5001'
blakqube_local_storage: './blakqube_cache'

# Logging
log_level: INFO

# Security
encryption_key: generate_a_secure_random_key_here

# Optional External Services
openai_api_key: your_openai_api_key
anthropic_api_key: your_anthropic_api_key
tavily_api_key: your_tavily_api_key
