import { IQubeTemplate } from '../../../../types/registry';

let templates: IQubeTemplate[] | null = null;

function seed(): IQubeTemplate[] {
  return [
    {
      id: 'template-001',
      name: 'Personal Data iQube',
      description: 'Template for storing and managing personal identity information with high security and privacy controls.',
      createdAt: '2025-08-15T12:00:00Z',
      iQubeType: 'DataQube',
      iQubeInstanceType: 'template',
      businessModel: 'Subscribe',
      sensitivityScore: 7,
      accuracyScore: 9,
      verifiabilityScore: 7,
      riskScore: 8,
    },
    {
      id: 'template-002',
      name: 'Financial Transaction iQube',
      description: 'Secure template for recording and verifying financial transactions with audit trails.',
      createdAt: '2025-08-10T14:30:00Z',
      iQubeType: 'DataQube',
      iQubeInstanceType: 'template',
      businessModel: 'Buy',
      sensitivityScore: 6,
      accuracyScore: 10,
      verifiabilityScore: 9,
      riskScore: 6,
    },
    {
      id: 'template-003',
      name: 'Content Verification iQube',
      description: 'Template for verifying the authenticity and provenance of digital content and media.',
      createdAt: '2025-08-05T09:15:00Z',
      iQubeType: 'ContentQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 3,
      accuracyScore: 8,
      verifiabilityScore: 10,
      riskScore: 4,
    },
    {
      id: 'liquidui-template-001',
      name: 'LiquidUI Drawer Grid (Catalog)',
      description: 'Catalog or gallery grid with drawer framing.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_v1' },
        { k: 'archetype', v: 'catalog_gallery' },
        { k: 'ratio_overrides', v: '{"featured":"16:9","standard":"4:3","grid":"1:1"}' },
      ],
    },
    {
      id: 'liquidui-template-002',
      name: 'LiquidUI Drawer Grid 1A (Feed Stream)',
      description: 'Feed-focused grid layout with a strong hero emphasis.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_1a' },
        { k: 'archetype', v: 'feed_stream' },
        { k: 'ratio_overrides', v: '{"featured":"16:9","standard":"4:3"}' },
      ],
    },
    {
      id: 'liquidui-template-003',
      name: 'LiquidUI Drawer Grid 1B (Search Results)',
      description: 'Search results grid with tighter density.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_1b' },
        { k: 'archetype', v: 'search_filter' },
        { k: 'ratio_overrides', v: '{"standard":"4:3","grid":"1:1"}' },
      ],
    },
    {
      id: 'liquidui-template-004',
      name: 'LiquidUI Drawer Grid 1C (Compare)',
      description: 'Featured comparison grid with a decision focus.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_1c' },
        { k: 'archetype', v: 'compare_decision' },
        { k: 'ratio_overrides', v: '{"featured":"16:9","standard":"4:3"}' },
      ],
    },
    {
      id: 'liquidui-template-005',
      name: 'LiquidUI Drawer Grid 2A (Dashboard)',
      description: 'Dashboard grid with KPIs and featured highlights.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_2a' },
        { k: 'archetype', v: 'dashboard_kpi' },
        { k: 'ratio_overrides', v: '{"featured":"16:9","standard":"4:3","grid":"1:1"}' },
      ],
    },
    {
      id: 'liquidui-template-006',
      name: 'LiquidUI Drawer Grid 2B (Workspace)',
      description: 'Workspace grid with list-detail emphasis.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_2b' },
        { k: 'archetype', v: 'workspace_table' },
      ],
    },
    {
      id: 'liquidui-template-007',
      name: 'LiquidUI Drawer Grid 2C (Entity Detail)',
      description: 'Entity detail grid with primary focus area.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_2c' },
        { k: 'archetype', v: 'entity_detail' },
      ],
    },
    {
      id: 'liquidui-template-008',
      name: 'LiquidUI Drawer Grid 3A (Inbox)',
      description: 'Inbox and thread list grid.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_3a' },
        { k: 'archetype', v: 'inbox_threads' },
      ],
    },
    {
      id: 'liquidui-template-009',
      name: 'LiquidUI Drawer Grid 3B (Community)',
      description: 'Community and forum grid.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:drawer_grid_3b' },
        { k: 'archetype', v: 'community_forum' },
      ],
    },
    {
      id: 'liquidui-template-010',
      name: 'LiquidUI Reader',
      description: 'Long-form reader and media viewer.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:reader_viewer_v1' },
        { k: 'archetype', v: 'reader_viewer' },
      ],
    },
    {
      id: 'liquidui-template-011',
      name: 'LiquidUI Timeline',
      description: 'Activity timeline and changelog.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:timeline_activity_v1' },
        { k: 'archetype', v: 'timeline_activity' },
      ],
    },
    {
      id: 'liquidui-template-012',
      name: 'LiquidUI Chat',
      description: 'Conversational chat and agent threads.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:chat_conversation_v1' },
        { k: 'archetype', v: 'chat_conversation' },
      ],
    },
    {
      id: 'liquidui-template-013',
      name: 'LiquidUI Live Room',
      description: 'Live meeting room for audio/video sessions.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:meeting_live_room_v1' },
        { k: 'archetype', v: 'meeting_live_room' },
      ],
    },
    {
      id: 'liquidui-template-014',
      name: 'LiquidUI Editor',
      description: 'Structured editor for creating and publishing.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:editor_compose_v1' },
        { k: 'archetype', v: 'editor_compose' },
      ],
    },
    {
      id: 'liquidui-template-015',
      name: 'LiquidUI Canvas',
      description: 'Spatial canvas for freeform work.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:canvas_workspace_v1' },
        { k: 'archetype', v: 'canvas_workspace' },
      ],
    },
    {
      id: 'liquidui-template-016',
      name: 'LiquidUI Builder',
      description: 'Builder or IDE workspace.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:builder_ide_v1' },
        { k: 'archetype', v: 'builder_ide' },
      ],
    },
    {
      id: 'liquidui-template-017',
      name: 'LiquidUI Notebook',
      description: 'Notebook and experiment lab.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:notebook_lab_v1' },
        { k: 'archetype', v: 'notebook_lab' },
      ],
    },
    {
      id: 'liquidui-template-018',
      name: 'LiquidUI Checkout',
      description: 'Checkout and payment flow.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:checkout_payment_v1' },
        { k: 'archetype', v: 'checkout_payment' },
      ],
    },
    {
      id: 'liquidui-template-019',
      name: 'LiquidUI Marketplace',
      description: 'Marketplace and exchange layout.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:marketplace_exchange_v1' },
        { k: 'archetype', v: 'marketplace_exchange' },
      ],
    },
    {
      id: 'liquidui-template-020',
      name: 'LiquidUI Board',
      description: 'Kanban or stage board.',
      createdAt: '2026-01-28T00:00:00Z',
      iQubeType: 'LiquidUITemplateArchetypeQube',
      iQubeInstanceType: 'template',
      businessModel: 'License',
      sensitivityScore: 0,
      accuracyScore: 5,
      verifiabilityScore: 5,
      riskScore: 0,
      metaExtras: [
        { k: 'liquid_template_id', v: 'liquidui:board_kanban_v1' },
        { k: 'archetype', v: 'board_kanban' },
      ],
    },
  ];
}

export function getStore(): IQubeTemplate[] {
  if (!templates) templates = seed();
  return templates;
}

export function setStore(next: IQubeTemplate[]) {
  templates = next;
}
