/**
 * Repo weight — the enforcement, not the cleanup.
 *
 * ── What happened ──────────────────────────────────────────────────────────
 *
 * The Amplify build failed with
 *
 *   CustomerError: The size of the build output (230813813) exceeds the max
 *   allowed size of 230686720 bytes.
 *
 * over by ~124 KB. The cause was not the change that tipped it: `target/` —
 * the Rust/ICP canister BUILD OUTPUT — had 879 files and 183.5 MB tracked in
 * git, more than half the repo, and was never in `.gitignore`. It was
 * untracked in the same change that added this file.
 *
 * ── Why a canary and not just the cleanup ──────────────────────────────────
 *
 * Operator, 2026-08-02:
 *
 *   > "the repo will continue to grow so we want to ensure dense materials
 *   >  are written to supabase and autodrive not to the repo as this will
 *   >  just kick the can down the road and will reappear in a few builds
 *   >  time"
 *
 * Exactly right. A one-time deletion buys headroom and changes no incentive:
 * the next agent to commit a manuscript, a corpus, a screenshot set or a
 * compiler artifact puts it straight back, and nobody learns until a deploy
 * breaks for everyone. Deploy-time is the worst possible moment to discover
 * it — the failure is remote, the message names a byte count rather than a
 * file, and the person who caused it is usually not the person debugging it.
 *
 * This test moves that discovery to the commit that causes it, and names the
 * file.
 *
 * ── What it does NOT claim ─────────────────────────────────────────────────
 *
 * Amplify's cap is on the DEPLOYMENT ARTIFACT, not on the repo: the repo feeds
 * it but the two are not equal, and the build output was smaller than the
 * tracked tree when this was written. So the budget below is a bound on what
 * the REPO carries — a directional guard, honestly framed. It is not a
 * prediction of the artifact size, and passing it is not a guarantee that a
 * deploy fits.
 */

import { describe, it, expect } from 'vitest';
import { execFileSync } from 'child_process';
import { statSync } from 'fs';
import { join } from 'path';

const ROOT = join(__dirname, '..');

/** One MB. A tracked file above this is an asset, not source. */
const MAX_TRACKED_FILE_BYTES = 1_048_576;

/**
 * Total tracked bytes, frozen at the post-cleanup measurement with ~10% of
 * room to work in. Not a target to grow into: crossing it means the corpus of
 * dense material in the repo has grown, which is the thing this file exists to
 * stop.
 */
const MAX_TRACKED_TOTAL_BYTES = 190_000_000;

/**
 * Build output. Regenerated by a tool, never authored, never committed —
 * `target/` alone was 183.5 MB.
 */
const BUILD_OUTPUT_PREFIXES = [
  'target/',
  '.next/',
  'node_modules/',
  'dist/',
  'out/',
  'coverage/',
  '.turbo/',
];

/**
 * Files over the per-file ceiling that already existed when this canary was
 * written. FROZEN: an entry may be REMOVED (move it to Supabase or Auto Drive
 * and delete it here), never added. A new oversize file fails the build and is
 * told where its bytes belong.
 *
 * Mostly design sources and render plates. They are debt, not permission.
 */
const GRANDFATHERED_OVERSIZE: ReadonlySet<string> = new Set([
  'artifacts/build-info/8e0b546c03e786b027ab3524a94e5b7d.json',
  'codexes/packs/irl/foundation/plates/canonical-plates-v0.9-superseded.png',
  'codexes/packs/irl/foundation/plates/canonical-plates-v1.0-reference.png',
  'package-lock.json',
  'public/images/demo/agentiq-tutorial.jpg',
  'public/images/demo/penny-digital.jpg',
  'public/images/demo/qripto-chronicles.jpg',
  'public/metaMe/sources/asset-specification-sheet.png',
  'public/metaMe/sources/iqube-copper-render-alt.png',
  'public/metaMe/sources/iqube-copper-render.png',
  'public/metaMe/sources/iqube-sand-render.png',
  'public/metaMe/sources/iqube-stone-render.png',
  'public/metaMe/sources/iqube-teal-render.png',
]);

function trackedFiles(): string[] {
  const out = execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, maxBuffer: 64 * 1024 * 1024 })
    .toString('utf8');
  return out.split('\0').filter(Boolean);
}

describe('repo weight — dense material does not live in git', () => {
  const files = trackedFiles();
  const sized = files.map((f) => {
    let size = 0;
    try {
      size = statSync(join(ROOT, f)).size;
    } catch {
      // A tracked path that is not on disk (submodule, case collision) is not
      // this canary's business — it contributes nothing to weight either.
    }
    return { file: f, size };
  });

  it('no build output is tracked', () => {
    const offenders = files.filter((f) => BUILD_OUTPUT_PREFIXES.some((p) => f.startsWith(p)));
    expect(
      offenders.slice(0, 20),
      `build output is committed (${offenders.length} file(s)). It is regenerated by its own tool and ` +
        'must be gitignored, not tracked. To fix: add the directory to .gitignore, then ' +
        '`git rm -r --cached <dir>`.',
    ).toEqual([]);
  });

  it('no NEW tracked file exceeds 1MB', () => {
    /*
     * Where the bytes belong instead (CLAUDE.md, "Dense Materials"):
     *   · Supabase Storage — working drafts, images, anything the app serves
     *   · Autonomys Auto Drive — canonical/frozen material needing a CID
     * and the repo carries the POINTER: cid, path, hash, provenance.
     */
    const offenders = sized
      .filter((s) => s.size > MAX_TRACKED_FILE_BYTES && !GRANDFATHERED_OVERSIZE.has(s.file))
      .map((s) => `${s.file} (${(s.size / 1048576).toFixed(1)} MB)`);
    expect(
      offenders,
      'these tracked files are over 1MB and are not grandfathered. Dense material belongs in Supabase ' +
        'Storage (working assets) or Autonomys Auto Drive (canonical artifacts); commit the CID or storage ' +
        `path and its provenance, never the bytes:\n${offenders.join('\n')}`,
    ).toEqual([]);
  });

  it('the grandfathered list only shrinks', () => {
    // An entry that no longer exists, or is no longer oversize, must be
    // REMOVED — otherwise the list stops describing real debt and starts
    // being a place to hide new debt.
    const stale: string[] = [];
    for (const f of GRANDFATHERED_OVERSIZE) {
      const row = sized.find((s) => s.file === f);
      if (!row || row.size <= MAX_TRACKED_FILE_BYTES) stale.push(f);
    }
    expect(
      stale,
      `these are grandfathered but no longer oversize (or no longer exist) — delete them from the list:\n${stale.join('\n')}`,
    ).toEqual([]);
  });

  it('total tracked bytes stay inside the budget', () => {
    const total = sized.reduce((a, s) => a + s.size, 0);
    expect(
      total,
      `the repo now carries ${(total / 1048576).toFixed(1)} MB of tracked files, over the ` +
        `${(MAX_TRACKED_TOTAL_BYTES / 1048576).toFixed(0)} MB budget. Raising this number is not the fix — ` +
        'find what grew (`git ls-files -z | xargs -0 stat -c "%s %n" | sort -rn | head`) and move it to ' +
        'Supabase or Auto Drive.',
    ).toBeLessThan(MAX_TRACKED_TOTAL_BYTES);
  });
});
