/**
 * Reciprocal Artifact Exchange — the generic type contract (PRD-IRL-AX-001).
 *
 * A GENERIC IRL capability: a bilateral, receipted exchange of independently
 * frozen research artifacts between two collaborating parties, gated by a
 * reciprocal disclosure policy and a lightweight signing ritual. This is NOT
 * an architecture-specific or OCSGA-specific feature — IRL-AX-001 (CI/IRL ×
 * OCSGA) is the first dogfood INSTANCE of this primitive, never baked into
 * the type/state-machine shape below.
 *
 * ── THE EVIDENTIARY CLAIM DISCIPLINE (PRD §2, non-negotiable) ───────────────
 *
 * The system may truthfully state: "Both artifacts were independently frozen
 * before formal exchange." It must NEVER state or imply that neither party
 * had prior knowledge of, discussion about, or access to the other's ideas —
 * that is a claim of informational isolation this capability does not and
 * cannot establish. `FORBIDDEN_ISOLATION_PHRASES` + `assertNoIsolationClaim`
 * below are the enforcement point; every UI string, receipt summary and
 * evidence record generated by this capability MUST pass that guard, and
 * `tests/reciprocal-exchange.test.ts` asserts it directly.
 *
 * ── STORAGE ──────────────────────────────────────────────────────────────
 *
 * Persisted in dedicated tables (supabase/migrations/*_reciprocal_artifact_
 * exchange.sql): `reciprocal_exchanges`, `exchange_artifacts`,
 * `exchange_attestations`, `exchange_receipts`, `exchange_comparisons`,
 * `exchange_derivatives`. Service-role RLS only — every read/write goes
 * through services/research/reciprocalExchange.ts, which resolves the caller
 * through the identity spine first (never a client-side Supabase read).
 */

// ─── State machine (PRD §11) ─────────────────────────────────────────────────

export const EXCHANGE_STATES = [
  'DRAFT',
  'A_DEPOSITED',
  'INVITED',
  'B_JOINED',
  'B_DEPOSITED',
  'READY_TO_SIGN',
  'A_SIGNED',
  'B_SIGNED',
  'EXCHANGED',
  'RECEIPT_ACKNOWLEDGED',
  'COMPARISON_OPEN',
  'COMPLETED',
] as const;
export type ExchangeState = (typeof EXCHANGE_STATES)[number];

/** Terminal/exception states (PRD §11). Reachable from most non-terminal
 *  states; never reachable FROM a terminal state (this file's transition
 *  table is the single source of truth for exactly which). */
export const EXCHANGE_EXCEPTION_STATES = [
  'DECLINED',
  'WITHDRAWN_PRE_EXCHANGE',
  'ARTIFACT_REPLACEMENT_REQUIRED',
  'SIGNATURE_EXPIRED',
  'DISPUTED',
  'REVOKED_ACCESS_POST_EXCHANGE',
] as const;
export type ExchangeExceptionState = (typeof EXCHANGE_EXCEPTION_STATES)[number];

export type ExchangeStatus = ExchangeState | ExchangeExceptionState;

/** States at/after which the exchange has crossed (reciprocal disclosure has
 *  occurred and cannot be un-crossed by any FORWARD transition — only a
 *  REVOCATION narrows future access, never rewrites this fact). */
export const CROSSED_STATES: readonly ExchangeStatus[] = [
  'EXCHANGED',
  'RECEIPT_ACKNOWLEDGED',
  'COMPARISON_OPEN',
  'COMPLETED',
  'REVOKED_ACCESS_POST_EXCHANGE',
];
export function hasCrossed(status: ExchangeStatus): boolean {
  return CROSSED_STATES.includes(status);
}

/**
 * Legal forward transitions. Deliberately does NOT assume a fixed A-then-B
 * signing order (PRD §11: "State machine implementation should model
 * independent required conditions rather than assume one fixed signature
 * order") — A_SIGNED and B_SIGNED are each reachable from READY_TO_SIGN
 * directly, and EXCHANGED is reachable from EITHER once both are satisfied
 * (the service layer's `isLegalExchangeTransition` used together with the
 * service's own dual-signature check, never state-machine order alone).
 */
const FORWARD_TRANSITIONS: Record<ExchangeStatus, ExchangeStatus[]> = {
  DRAFT: ['A_DEPOSITED', 'WITHDRAWN_PRE_EXCHANGE', 'DECLINED'],
  A_DEPOSITED: ['INVITED', 'WITHDRAWN_PRE_EXCHANGE', 'DECLINED'],
  INVITED: ['B_JOINED', 'WITHDRAWN_PRE_EXCHANGE', 'DECLINED'],
  B_JOINED: ['B_DEPOSITED', 'WITHDRAWN_PRE_EXCHANGE', 'DECLINED'],
  B_DEPOSITED: ['READY_TO_SIGN', 'WITHDRAWN_PRE_EXCHANGE', 'DECLINED', 'ARTIFACT_REPLACEMENT_REQUIRED'],
  READY_TO_SIGN: [
    'A_SIGNED',
    'B_SIGNED',
    'EXCHANGED',
    'WITHDRAWN_PRE_EXCHANGE',
    'DECLINED',
    'SIGNATURE_EXPIRED',
    'ARTIFACT_REPLACEMENT_REQUIRED',
  ],
  A_SIGNED: ['B_SIGNED', 'EXCHANGED', 'WITHDRAWN_PRE_EXCHANGE', 'SIGNATURE_EXPIRED', 'ARTIFACT_REPLACEMENT_REQUIRED'],
  B_SIGNED: ['A_SIGNED', 'EXCHANGED', 'WITHDRAWN_PRE_EXCHANGE', 'SIGNATURE_EXPIRED', 'ARTIFACT_REPLACEMENT_REQUIRED'],
  EXCHANGED: ['RECEIPT_ACKNOWLEDGED', 'REVOKED_ACCESS_POST_EXCHANGE', 'DISPUTED'],
  RECEIPT_ACKNOWLEDGED: ['COMPARISON_OPEN', 'REVOKED_ACCESS_POST_EXCHANGE', 'DISPUTED'],
  COMPARISON_OPEN: ['COMPLETED', 'REVOKED_ACCESS_POST_EXCHANGE', 'DISPUTED'],
  COMPLETED: ['REVOKED_ACCESS_POST_EXCHANGE', 'DISPUTED'],
  // Exception states are terminal for FORWARD progress. DISPUTED may later be
  // resolved by an operator-governed act outside this state machine's own
  // vocabulary (not modelled here — PRD does not specify a dispute-resolution
  // transition, and inventing one would be exactly the kind of unrequested
  // scope this build stays clear of).
  DECLINED: [],
  WITHDRAWN_PRE_EXCHANGE: [],
  ARTIFACT_REPLACEMENT_REQUIRED: ['B_DEPOSITED', 'READY_TO_SIGN'],
  SIGNATURE_EXPIRED: ['READY_TO_SIGN'],
  DISPUTED: [],
  REVOKED_ACCESS_POST_EXCHANGE: [],
};

export function isLegalExchangeTransition(from: ExchangeStatus, to: ExchangeStatus): boolean {
  return (FORWARD_TRANSITIONS[from] ?? []).includes(to);
}

// ─── Disclosure policy (PRD §12) ─────────────────────────────────────────────

export const DISCLOSURE_POLICIES = [
  'RECIPROCAL_AFTER_BOTH_DEPOSIT',
  'IMMEDIATE_ON_DEPOSIT',
  'MANIFEST_BEFORE_CONTENT',
] as const;
export type DisclosurePolicy = (typeof DISCLOSURE_POLICIES)[number];

// ─── Comparison classification vocabulary (PRD §15, §21) ────────────────────

export const COMPARISON_CLASSIFICATIONS = [
  'COMPATIBLE',
  'AMBIGUOUS',
  'CONFLICTING',
  'REDUNDANT',
  'UNRESOLVED',
] as const;
export type ComparisonClassification = (typeof COMPARISON_CLASSIFICATIONS)[number];

export const COMPATIBILITY_KINDS = ['DISCOVERED', 'CREATED'] as const;
export type CompatibilityKind = (typeof COMPATIBILITY_KINDS)[number];

// ─── Artifact model (PRD §7) ─────────────────────────────────────────────────

export const ARTIFACT_SOURCE_TYPES = ['upload', 'repository-commit', 'immutable-reference', 'manifest'] as const;
export type ArtifactSourceType = (typeof ARTIFACT_SOURCE_TYPES)[number];

/** Which of the two exchange slots an artifact/attestation belongs to.
 *  Deliberately A/B, not "initiator/counterparty" — a party's ROLE in the
 *  exchange (who created it) is fixed at DRAFT; PartySlot is the stable key
 *  every downstream table joins on. */
export type PartySlot = 'A' | 'B';

/**
 * Which interaction channel originated a piece of evidence (Surface
 * Independence of Constitutional Acts, 2026-08-26). Additive, honesty-only —
 * it never changes what counts as valid evidence (the SAME canonical
 * service writes both), only how the record labels its own provenance.
 * 'native-ui' is the default for every row written before this field
 * existed and for every native-surface write going forward; 'mcp' marks a
 * write an authenticated MCP tool originated on the principal's behalf. See
 * services/threshold/mcpConstitutionalActs.ts.
 */
export type EvidenceOriginChannel = 'native-ui' | 'mcp';

export interface ExchangeArtifactRecord {
  id: string;
  exchangeId: string;
  party: PartySlot;
  title: string;
  artifactClass: string;
  description: string | null;
  version: number;
  sourceType: ArtifactSourceType;
  sourceReference: string;
  contentHash: string | null;
  repositoryCommit: string | null;
  storageReference: string | null;
  mimeType: string | null;
  confidentialityClass: string;
  ownershipDeclaration: string;
  rightsForExchange: string;
  supersedesArtifactId: string | null;
  depositedAt: string;
  depositReceiptId: string | null;
  originChannel: EvidenceOriginChannel;
}

// ─── Attestation model (PRD §8–9, §17) ───────────────────────────────────────

export const ATTESTATION_ACT_TYPES = [
  'freeze_declaration',
  'instrument_signature',
  'receipt_acknowledgment',
] as const;
export type AttestationActType = (typeof ATTESTATION_ACT_TYPES)[number];

/** Who actually performed the act. A delegated agent may assist the workflow
 *  mechanics, but `freeze_declaration` and `instrument_signature` MUST be
 *  `principal` — enforced server-side via resolveConstitutionalContext, never
 *  trusted from client input (see services/research/reciprocalExchange.ts). */
export type ActorType = 'principal' | 'delegated_agent';

export interface ExchangeAttestationRecord {
  id: string;
  exchangeId: string;
  party: PartySlot;
  actType: AttestationActType;
  /** Snapshot of the artifact version this attestation covers — freeze and
   *  signature attestations are pinned to a version so a later
   *  ARTIFACT_REPLACEMENT invalidates them WITHOUT deleting or editing this
   *  row (append-only evidence, PRD §17/§21). Null for receipt_acknowledgment
   *  (which covers the exchange, not one artifact version). */
   artifactVersion: number | null;
  actorType: ActorType;
  statementText: string;
  attestedAt: string;
  receiptId: string | null;
  originChannel: EvidenceOriginChannel;
}

// ─── The canonical freeze declaration + instrument text (PRD §8, §9) ────────

/** PRD §8's freeze declaration, materially equivalent wording — reused
 *  verbatim by the service and the UI so there is exactly one canonical
 *  string, never a paraphrase drifting from what was actually attested. */
export const FREEZE_DECLARATION_TEXT =
  'I declare that this artifact represents the version independently frozen by my party for this exchange. ' +
  'I understand that subsequent modifications will be recorded as derivative versions and will not alter ' +
  'the provenance of this frozen baseline.';

/** PRD §9 Stage 3's eight instrument acknowledgments, canonical order. */
export const EXCHANGE_INSTRUMENT_CLAUSES: readonly string[] = [
  'the identity/persona under which I participate',
  'the artifact(s) I deposited',
  'the declared freeze/version status',
  'the agreed research purpose',
  'the confidentiality/IP terms applicable to this exchange',
  'that receipt does not transfer ownership unless separately agreed',
  'that subsequent comparison must preserve source artifacts',
  'that later normalization/redesign is derivative work, not evidence of native compatibility',
];

// ─── The isolation-claim guard (PRD §2 — CRITICAL) ──────────────────────────

/**
 * Phrases that assert or imply informational isolation between the parties.
 * ANY generated string (UI copy, receipt summary, evidence record) that
 * contains one of these is a constitutional defect for this capability — it
 * overstates what independent-freeze provenance can honestly establish.
 * Case-insensitive substring match; deliberately broad rather than narrow, on
 * the theory that a false negative here is far more costly than a false
 * positive that makes a legitimate string slightly reword itself.
 */
export const FORBIDDEN_ISOLATION_PHRASES: readonly string[] = [
  'neither party had prior knowledge',
  'no prior knowledge of',
  'no prior access to',
  'without prior knowledge of each other',
  'had no access to the other',
  'had no knowledge of the other',
  'informational isolation',
  'developed in isolation from each other',
  'never discussed',
  'never had access to',
  'blind to each other',
  'without any prior contact',
];

/** The one claim this capability IS allowed to make (PRD §2, §10). */
export const INDEPENDENT_FREEZE_CLAIM =
  'Both artifacts were independently frozen before formal exchange.';

export class IsolationClaimViolation extends Error {
  constructor(public readonly matchedPhrase: string, public readonly text: string) {
    super(
      `Generated text asserts an informational-isolation claim ("${matchedPhrase}"), which this capability ` +
        `must never claim — only "${INDEPENDENT_FREEZE_CLAIM}" is a truthful claim here.`,
    );
    this.name = 'IsolationClaimViolation';
  }
}

/** Throws IsolationClaimViolation if `text` contains a forbidden phrase.
 *  Call this on every generated summary/copy string before it is persisted
 *  to a receipt, evidence record, or rendered UI string for this capability. */
export function assertNoIsolationClaim(text: string): void {
  const lower = text.toLowerCase();
  for (const phrase of FORBIDDEN_ISOLATION_PHRASES) {
    if (lower.includes(phrase)) throw new IsolationClaimViolation(phrase, text);
  }
}

// ─── The exchange record (PRD §6) ────────────────────────────────────────────

export const EXCHANGE_TYPES = ['independent-artifact-comparison'] as const;
export type ExchangeType = (typeof EXCHANGE_TYPES)[number];

export interface ReciprocalExchangeRecord {
  id: string;
  exchangeType: ExchangeType;
  title: string;
  purpose: string;
  researchQuestion: string | null;
  /** Party A — the initiator. Always a resolved persona (creation requires
   *  a signed-in principal). */
  initiatorPersonaId: string;
  /** Party B — the counterparty. Null until claimed via the exchange's own
   *  invite code (B_JOINED). */
  counterpartyPersonaId: string | null;
  researchSpaceId: string | null;
  cohortId: string | null;
  status: ExchangeStatus;
  disclosurePolicy: DisclosurePolicy;
  comparisonPolicy: string | null;
  confidentialityClass: string;
  permittedPurpose: string;
  ownershipDeclaration: string;
  derivativeAnalysisPermitted: boolean;
  publicationPermitted: boolean;
  retentionPolicy: string | null;
  agreementRef: string | null;
  /** sha256 of the raw invite code — the code itself is never stored (same
   *  discipline as access_invitations.code_hash). Null once claimed or when
   *  no counterparty invitation has been issued yet. */
  inviteCodeHash: string | null;
  inviteExpiresAt: string | null;
  qubetalkChannelId: string | null;
  parentExperimentId: string | null;
  derivedExperimentId: string | null;
  createdAt: string;
  openedAt: string | null;
  completedAt: string | null;
}

export interface ExchangeReceiptRecord {
  id: string;
  exchangeId: string;
  /** The generic activity_receipts row this rides on (DVN-anchorable). */
  activityReceiptId: string | null;
  partyAArtifactId: string;
  partyBArtifactId: string;
  partyAArtifactVersion: number;
  partyBArtifactVersion: number;
  partyAFingerprint: string | null;
  partyBFingerprint: string | null;
  partyAFreezeAttestationId: string;
  partyBFreezeAttestationId: string;
  partyASignatureAttestationId: string;
  partyBSignatureAttestationId: string;
  disclosurePolicy: DisclosurePolicy;
  confidentialityClassRef: string;
  purpose: string;
  crossedAt: string;
  /** PRD §10's human-readable compression — generated ONCE at crossing and
   *  frozen on the row so it can never later drift from what actually
   *  happened. MUST pass assertNoIsolationClaim before being written. */
  humanReadableSummary: string;
}

export interface ExchangeComparisonRecord {
  id: string;
  exchangeId: string;
  /** Both frozen artifact ids at the version that crossed — immutable link;
   *  the comparison view must never allow editing either. */
  partyAArtifactId: string;
  partyBArtifactId: string;
  openedAt: string;
  openedByPersonaId: string;
  status: 'open' | 'closed';
}

export interface ExchangeDerivativeRecord {
  id: string;
  comparisonId: string;
  exchangeId: string;
  title: string;
  description: string;
  /** Never the frozen source artifact ids' rows themselves — a lineage
   *  pointer, not a mutation. */
  sourceArtifactIds: string[];
  classification: ComparisonClassification | null;
  compatibilityKind: CompatibilityKind | null;
  createdByPersonaId: string;
  createdAt: string;
}
