"use client";

/**
 * /article — Public share-link landing page
 *
 * Handles URLs generated by SocialSharingModal:
 *   /article?id=<contentId>&shareId=<shareId>&persona=<personaId>&title=...
 *
 * Tracks the click, then renders the content via the SmartTriad ContentViewer.
 */

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import ContentViewer from "@/app/components/content/ContentViewer";
import type { SmartContentQube } from "@/types/smartContent";

function ArticlePage() {
  const searchParams = useSearchParams();
  const contentId = searchParams.get("id");
  const shareId = searchParams.get("shareId");
  const personaId = searchParams.get("persona");

  const [content, setContent] = useState<SmartContentQube | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Track share click and fetch content
  useEffect(() => {
    if (!contentId) {
      setError("No content ID provided.");
      setLoading(false);
      return;
    }

    // Track click (fire and forget)
    if (shareId) {
      fetch("/api/social/track", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          shareId,
          personaId: personaId || null,
          contentId,
          eventType: "click",
        }),
      }).catch(() => {});
    }

    // Fetch content
    fetch(`/api/content/smart/${contentId}`)
      .then(res => res.ok ? res.json() : Promise.reject(res.statusText))
      .then(data => {
        const item: SmartContentQube = data.data || data;
        setContent(item);
        setLoading(false);
      })
      .catch(err => {
        setError(`Failed to load content: ${err}`);
        setLoading(false);
      });
  }, [contentId, shareId, personaId]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-900 text-white">
        <div className="text-slate-400">Loading…</div>
      </div>
    );
  }

  if (error || !content) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-slate-900 text-white">
        <div className="text-center">
          <p className="text-slate-400">{error || "Content not found."}</p>
          <a href="/" className="mt-4 inline-block text-sm text-amber-400 underline">
            Go to AigentZ
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-900 text-white">
      <ContentViewer
        content={content}
        hasAccess={false}
        accessScope="preview"
        initialModality="read"
        onClose={() => {
          if (typeof window !== "undefined") window.history.back();
        }}
      />
    </div>
  );
}

export default function ArticleSharePage() {
  return (
    <Suspense
      fallback={
        <div className="flex min-h-screen items-center justify-center bg-slate-900 text-white">
          <div className="text-slate-400">Loading…</div>
        </div>
      }
    >
      <ArticlePage />
    </Suspense>
  );
}
