/**
 * Runtime-download loader for @napi-rs/canvas's native binary.
 *
 * `@napi-rs/canvas-linux-x64-gnu`'s ONE file, skia.linux-x64-gnu.node, is
 * 33,253,808 bytes -- the single largest package traced into the Amplify SSR
 * standalone artifact (2026-09-07 build-size forensic investigation), used by
 * exactly two routes (app/api/content/pdf-page/[cid],
 * app/api/content/pdf-page-by-master/[masterId]) to rasterize a single PDF
 * page to PNG. Bundling it costs every Lambda invocation ~32 MB against the
 * 230,686,720-byte hard cap regardless of whether that request ever renders a
 * PDF page.
 *
 * This mirrors the EXISTING, shipped precedent for exactly this problem:
 * app/api/skills/video/_thumbnail.ts's ffmpeg-static loader (~80 MB binary,
 * excluded from tracing, fetched into /tmp on first use, cached for the
 * container's lifetime). The mechanism differs because the two binaries load
 * differently -- ffmpeg-static is spawned as an independent OS process
 * (`child_process.spawn`), so any executable file on disk works; a napi-rs
 * native addon is `require()`d in-process via Node's `process.dlopen()` --
 * but @napi-rs/canvas's own generated loader (node_modules/@napi-rs/canvas/
 * js-binding.js, auto-generated by NAPI-RS, the same generator every napi-rs
 * package uses) explicitly supports this: `requireNative()` checks
 * `process.env.NAPI_RS_NATIVE_LIBRARY_PATH` FIRST, before any of its
 * platform-specific fallback paths, and does `require(<that path>)` --
 * Node's `.node` loader works identically whether the file lives in
 * node_modules or anywhere else on disk. This is a first-class, documented
 * napi-rs mechanism, not a module-resolution hack.
 *
 * Source: the exact npm registry tarball for the version package-lock.json
 * already pins (0.1.88) -- an immutable, content-addressed release, the same
 * artifact `npm ci` would have installed. Verified 2026-09-07: downloading
 * this tarball and extracting skia.linux-x64-gnu.node reproduces this
 * environment's own installed copy byte-for-byte (same SHA-256, same size).
 */

import { createHash } from "crypto";
import { mkdir, writeFile, access, chmod, rename, stat } from "fs/promises";
import { gunzipSync } from "zlib";

// Pinned to package-lock.json's resolved version for
// node_modules/@napi-rs/canvas-linux-x64-gnu. Bump BOTH this and the two
// constants below together if that resolved version ever changes (a
// mismatched hash fails closed -- see verifyAndExtract below -- so a stale
// pin cannot silently serve the wrong binary).
const NAPI_CANVAS_PACKAGE_VERSION = "0.1.88";
const NAPI_CANVAS_TARBALL_URL = `https://registry.npmjs.org/@napi-rs/canvas-linux-x64-gnu/-/canvas-linux-x64-gnu-${NAPI_CANVAS_PACKAGE_VERSION}.tgz`;
// SHA-256 of the EXTRACTED skia.linux-x64-gnu.node file itself (not the
// tarball) -- computed 2026-09-07 against this repo's own `npm ci`-installed
// copy at this exact version.
const NAPI_CANVAS_BINARY_SHA256 = "3ebf549df87c6c463c3f42f6e57829435ae26f6b430b6b324754c080b9975ead";
const NAPI_CANVAS_BINARY_BYTES = 33253808;
const NAPI_CANVAS_TAR_ENTRY_PATH = "package/skia.linux-x64-gnu.node";

const NAPI_CANVAS_TMP_DIR = "/tmp/napi-canvas-bin";
const NAPI_CANVAS_TMP_PATH = `${NAPI_CANVAS_TMP_DIR}/skia.linux-x64-gnu-${NAPI_CANVAS_PACKAGE_VERSION}.node`;
const NAPI_CANVAS_DOWNLOAD_TIMEOUT_MS = 60_000;

/**
 * Minimal USTAR reader for exactly one known entry. npm tarballs are plain
 * gzip'd tar archives; we do not need general tar support, only to locate
 * ONE file by its exact path and read its declared size -- a 512-byte header
 * per entry (name in the first 100 bytes, octal size at offset 124, length
 * 12), content padded to a 512-byte boundary. No new dependency (no `tar`
 * package is a direct dependency of this repo) for a single, well-defined
 * extraction.
 */
function extractTarEntry(tarBuffer: Buffer, entryPath: string): Buffer {
  let offset = 0;
  while (offset + 512 <= tarBuffer.length) {
    const header = tarBuffer.subarray(offset, offset + 512);
    // Two consecutive all-zero header blocks mark the end of the archive.
    if (header.every((b) => b === 0)) break;
    const name = header.subarray(0, 100).toString("utf8").replace(/\0.*$/, "");
    const sizeOctal = header.subarray(124, 136).toString("utf8").replace(/\0.*$/, "").trim();
    const size = parseInt(sizeOctal, 8) || 0;
    const dataStart = offset + 512;
    if (name === entryPath) {
      return Buffer.from(tarBuffer.subarray(dataStart, dataStart + size));
    }
    const paddedSize = Math.ceil(size / 512) * 512;
    offset = dataStart + paddedSize;
  }
  throw new Error(`tar entry not found: ${entryPath}`);
}

function verifyBinary(binary: Buffer): void {
  if (binary.byteLength !== NAPI_CANVAS_BINARY_BYTES) {
    throw new Error(
      `@napi-rs/canvas native binary size mismatch: expected ${NAPI_CANVAS_BINARY_BYTES} bytes, got ${binary.byteLength}`,
    );
  }
  const actualHash = createHash("sha256").update(binary).digest("hex");
  if (actualHash !== NAPI_CANVAS_BINARY_SHA256) {
    throw new Error(
      `@napi-rs/canvas native binary SHA-256 mismatch: expected ${NAPI_CANVAS_BINARY_SHA256}, got ${actualHash}`,
    );
  }
}

// Dedup concurrent downloads within one warm container.
let downloadInFlight: Promise<string> | null = null;

async function downloadNativeBindingToTmp(): Promise<string> {
  if (!downloadInFlight) {
    downloadInFlight = (async () => {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), NAPI_CANVAS_DOWNLOAD_TIMEOUT_MS);
      try {
        const res = await fetch(NAPI_CANVAS_TARBALL_URL, { redirect: "follow", signal: controller.signal });
        if (!res.ok) throw new Error(`@napi-rs/canvas binary download ${res.status} from ${NAPI_CANVAS_TARBALL_URL}`);
        const gz = Buffer.from(await res.arrayBuffer());
        const tar = gunzipSync(gz);
        const binary = extractTarEntry(tar, NAPI_CANVAS_TAR_ENTRY_PATH);
        verifyBinary(binary);

        await mkdir(NAPI_CANVAS_TMP_DIR, { recursive: true });
        // Write-then-rename so a concurrent reader never sees a partial file.
        const partial = `${NAPI_CANVAS_TMP_PATH}.${process.pid}.partial`;
        await writeFile(partial, binary);
        await chmod(partial, 0o755);
        await rename(partial, NAPI_CANVAS_TMP_PATH);
        console.log(
          `[napi-canvas] downloaded and verified ${Math.round(binary.byteLength / 1024 / 1024)}MB native binary to ${NAPI_CANVAS_TMP_PATH}`,
        );
        return NAPI_CANVAS_TMP_PATH;
      } finally {
        clearTimeout(timer);
      }
    })().catch((err) => {
      downloadInFlight = null; // allow retry on the next call
      throw err;
    });
  }
  return downloadInFlight;
}

/**
 * Ensures @napi-rs/canvas's native binary is available and points
 * NAPI_RS_NATIVE_LIBRARY_PATH at it, THEN returns. Callers MUST await this
 * before the first `import('@napi-rs/canvas')` in this process -- the
 * package reads the env var at module-load time (see js-binding.js's
 * requireNative()), not per-call.
 */
export async function ensureNapiCanvasNativeBinding(): Promise<void> {
  // Already resolved in this process (either a prior call already set it, or
  // the operator provided their own override).
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      await access(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
      return;
    } catch {
      // Configured path is stale/missing -- fall through and re-resolve.
    }
  }
  // Already fetched this container lifetime.
  try {
    const s = await stat(NAPI_CANVAS_TMP_PATH);
    if (s.size === NAPI_CANVAS_BINARY_BYTES) {
      process.env.NAPI_RS_NATIVE_LIBRARY_PATH = NAPI_CANVAS_TMP_PATH;
      return;
    }
  } catch {
    /* fall through to download */
  }
  const path = await downloadNativeBindingToTmp();
  process.env.NAPI_RS_NATIVE_LIBRARY_PATH = path;
}
