/**
 * Icon Mapping Utility
 *
 * Maps icon names from codex configuration to Lucide React components
 */

import {
  BookOpen,
  Users,
  Scroll,
  Gamepad2,
  Globe,
  Crown,
  Sparkles,
  Home,
  Mountain,
  Shield,
  Star,
  Coins,
  Brain,
  Gift,
  FileText,
  Code,
  GraduationCap,
  Newspaper,
  Zap,
  Circle,
  BookMarked,
  TrendingUp,
  Megaphone,
  Wand2,
  Cpu,
  Settings,
  Layers,
  Route,
  Bitcoin,
  Grid3x3,
  BarChart3,
  MessageSquare,
  Package,
  PackageCheck,
  Boxes,
  Hexagon,
  Target,
  Activity,
  FolderOpen,
  Heart,
  Briefcase,
  Award,
  BarChart2,
  BookOpenCheck,
  Bot,
  Box,
  CheckCircle,
  CheckSquare,
  ClipboardList,
  Code2,
  Compass,
  Database,
  DollarSign,
  Factory,
  FileBadge,
  FileCheck,
  FileCheck2,
  FileEdit,
  FileSearch,
  FileSignature,
  Film,
  FlaskConical,
  Gauge,
  Gavel,
  GitBranch,
  GitCommit,
  Grid3X3,
  Hammer,
  Handshake,
  History,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Library,
  LifeBuoy,
  Link2,
  ListTodo,
  Lock,
  Map,
  MessageCircle,
  Milestone,
  Network,
  PenSquare,
  PenTool,
  Plane,
  Radio,
  Receipt,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  Send,
  ShieldCheck,
  ShoppingBag,
  User,
  UserSquare,
  Vault,
  Wallet,
  Wrench,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  BookOpen,
  Users,
  Scroll,
  Gamepad2,
  Globe,
  Crown,
  Sparkles,
  Home,
  Mountain,
  Shield,
  Star,
  Coins,
  Brain,
  Gift,
  FileText,
  Code,
  GraduationCap,
  Newspaper,
  Zap,
  Circle,
  BookMarked,
  TrendingUp,
  Megaphone,
  Wand2,
  Cpu,
  Settings,
  Layers,
  Route,
  Bitcoin,
  Grid3x3,
  BarChart: BarChart3,
  BarChart3,
  MessageSquare,
  Package,
  PackageCheck,
  Boxes,
  Hexagon,
  Target,
  Activity,
  FolderOpen,
  Heart,
  Briefcase,
  // ── Registered 2026-07-27 ──────────────────────────────────────────────
  // These 56 names were already used by `metadata.icon` across
  // data/codex-configs.ts but had never been added here, so
  // getIconComponent fell through to `Circle` and rendered a blank dot.
  // More than half the platform's tab icons were inert (MS-7 — an inert
  // mechanism is a defect even though nothing errors). Every name below is
  // a verified lucide-react export; `tests/codex-icons.test.ts` now fails
  // the build if a config ever names an icon this map does not carry.
  Award,
  BarChart2,
  BookOpenCheck,
  Bot,
  Box,
  CheckCircle,
  CheckSquare,
  ClipboardList,
  Code2,
  Compass,
  Database,
  DollarSign,
  Factory,
  FileBadge,
  FileCheck,
  FileCheck2,
  FileEdit,
  FileSearch,
  FileSignature,
  Film,
  FlaskConical,
  Gauge,
  Gavel,
  GitBranch,
  GitCommit,
  Grid3X3,
  Hammer,
  Handshake,
  History,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  Library,
  LifeBuoy,
  Link2,
  ListTodo,
  Lock,
  Map,
  MessageCircle,
  Milestone,
  Network,
  PenSquare,
  PenTool,
  Plane,
  Radio,
  Receipt,
  RefreshCw,
  Rocket,
  Scale,
  Search,
  Send,
  ShieldCheck,
  ShoppingBag,
  User,
  UserSquare,
  Vault,
  Wallet,
  Wrench,
};

/**
 * Get Lucide icon component by name
 * Falls back to Circle if icon not found
 */
export function getIconComponent(iconName?: string): LucideIcon {
  if (!iconName) return Circle;
  return ICON_MAP[iconName] || Circle;
}

/**
 * Get all available icon names
 */
export function getAvailableIcons(): string[] {
  return Object.keys(ICON_MAP);
}
