import { getSupabaseServer } from '@/app/api/_lib/supabaseServer';

const TABLE = 'agent_gateway_sessions';

export type AdoptedPersonaSwitch = {
  handshakeCode: string;
  requestedScope: string[];
  initiatingService: string;
  targetPrincipalPublicRef: string;
  expiresAt: string | null;
};

/**
 * Bind a previously prepared persona-switch intent to the OAuth parameters
 * generated by the MCP HOST during re-authorization.
 *
 * request_persona_switch is a constitutional intent, not an OAuth client. An
 * agent/model cannot manufacture correlation state or a PKCE verifier on behalf
 * of Claude/ChatGPT/etc. The MCP host must own those values. When the transport
 * challenges the current bearer, the host starts a normal OAuth authorization
 * flow; authorize-init calls this function to replace the provisional tool-call
 * values with the host-generated state/challenge before any human authorization
 * code can be issued.
 */
export async function adoptPendingPersonaSwitchForOAuth(input: {
  clientId: string;
  redirectUri: string;
  pkceChallenge: string;
  oauthState: string;
}): Promise<AdoptedPersonaSwitch | null> {
  const admin = getSupabaseServer();
  if (!admin) return null;

  const { data: rows, error } = await admin
    .from(TABLE)
    .select('id,handshake_code,status,requested_scope,initiating_service,target_principal_public_ref,expires_at,supersedes_session_id,pkce_challenge,oauth_state')
    .eq('client_id', input.clientId)
    .eq('redirect_uri', input.redirectUri)
    .eq('transition_kind', 'persona_switch')
    .eq('status', 'pending')
    .order('expires_at', { ascending: false })
    .limit(1);
  if (error || !rows?.length) return null;

  const row = rows[0] as Record<string, unknown>;
  const expiresAt = typeof row.expires_at === 'string' ? row.expires_at : null;
  if (expiresAt && new Date(expiresAt).getTime() < Date.now()) return null;
  if (typeof row.supersedes_session_id !== 'string' || typeof row.target_principal_public_ref !== 'string') return null;

  // The source session must still be the active constitutional crossing. This
  // is deliberately checked again at adoption time rather than trusting the
  // earlier tool call.
  const { data: source } = await admin
    .from(TABLE)
    .select('id,status,expires_at')
    .eq('id', row.supersedes_session_id)
    .maybeSingle();
  if (!source || source.status !== 'active') return null;
  if (source.expires_at && new Date(source.expires_at).getTime() < Date.now()) return null;

  const { data: updated, error: updateError } = await admin
    .from(TABLE)
    .update({
      pkce_challenge: input.pkceChallenge,
      oauth_state: input.oauthState,
    })
    .eq('id', row.id)
    .eq('status', 'pending')
    .select('handshake_code,requested_scope,initiating_service,target_principal_public_ref,expires_at');
  if (updateError || !updated?.length) return null;

  const claimed = updated[0] as Record<string, unknown>;
  return {
    handshakeCode: String(claimed.handshake_code),
    requestedScope: Array.isArray(claimed.requested_scope) ? claimed.requested_scope.map(String) : [],
    initiatingService: String(claimed.initiating_service || 'polity-passport'),
    targetPrincipalPublicRef: String(claimed.target_principal_public_ref),
    expiresAt: typeof claimed.expires_at === 'string' ? claimed.expires_at : null,
  };
}
