"use client";

/**
 * ExpandedNBEPill — the protocol Pill (compact action unit) once it has
 * been acted on. Renders as a state-coloured container that folds the
 * follow-on Pills generated by the original Act: specialist response,
 * drafted artifact(s), and the second-tier approval gate.
 *
 * Three-state colour scheme (matches the protocol nomenclature):
 *   - amber  → pending (approval required, pre-Act)   — NOT this component
 *   - blue   → queued (Act fired, awaiting execution) — this component
 *   - green  → complete (artifact delivered / external action confirmed)
 *
 * Pre-Act pills render as regular NextBestActionCard with the amber
 * approvalRequired chip. Once Act fires and queuedState is set, the
 * parent template (BriefCard, VentureProgressCard, MoveForwardCapsule)
 * swaps the NextBestActionCard for THIS component so the user sees one
 * continuous container with everything the pill spawned.
 *
 * Composition lives here, not in the parent template, so the same pill
 * presentation is shared across every action template.
 */

import React from "react";
import { Check, CheckCircle2, Loader2, X, Users, Sparkles, CheckSquare } from "lucide-react";
import type { NextBestActionData } from "@/components/metame/cards/NextBestActionCard";
import {
  SpecialistResponseCard,
  type SpecialistResponseData,
} from "@/components/metame/cards/SpecialistResponseCard";
import { ArtifactCard, type ArtifactCardData } from "@/components/metame/cards/ArtifactCard";
import { SecondTierApprovalCard } from "@/components/metame/cards/SecondTierApprovalCard";
import type { IqubeKind } from "@/components/metame/cards/IqubeContextDisclosure";

export interface ExpandedNBEPillQueuedState {
  intentId: string;
  status: string;
  queueMessage: string;
  /**
   * Operator-applied terminal flag — flips the pill to the green
   * "complete" state without needing an actual connector-success
   * signal. Useful in alpha when execution is mocked (Phase 5/6
   * specialist routing not live yet) and the operator needs explicit
   * control over pill lifecycle.
   */
  manuallyComplete?: boolean;
}

export interface ExpandedNBEPillSecondTier {
  artifactId: string;
  connectorId: string;
  connectorLabel: string;
  summary: string;
  detail?: string;
  submitting: boolean;
  error: string | null;
}

interface Props {
  action: NextBestActionData;
  queued: ExpandedNBEPillQueuedState;
  /** Specialist response keyed to this NBE, if one has been resolved. */
  specialistResponse?: SpecialistResponseData | null;
  specialistLoading?: boolean;
  specialistError?: string | null;
  /** Artifacts whose intentId matches `queued.intentId`. */
  artifacts: ArtifactCardData[];
  /** Active second-tier approval, if it targets an artifact in this pill. */
  secondTierApproval?: ExpandedNBEPillSecondTier | null;
  using: IqubeKind[];
  actionPendingArtifactId?: string | null;
  actionErrors?: Record<string, string>;
  onDismissQueued: () => void;
  onDismissSpecialist?: () => void;
  onUseSuggestedArtifact?: (artifactType: string, response: SpecialistResponseData) => void;
  onSendArtifact: (artifactId: string) => void;
  onDismissArtifact: (artifactId: string) => void;
  onApproveSecondTier?: () => void;
  onCancelSecondTier?: () => void;
  /** Operator-driven complete flip — surfaces a "Mark complete" button
   *  in the pill header so the user can advance pill state to green
   *  even when no artifact-level execution signal has fired. */
  onMarkComplete?: () => void;
  theme?: "light" | "dark";
}

const CARTRIDGE_LABELS: Record<string, string> = {
  metame: "metaMe",
  knyt: "KNYT",
  qriptopian: "The Qriptopian",
  marketa: "Marketa",
  avl: "metaMe Venture Lab",
};

const SPECIALIST_LABELS: Record<string, string> = {
  marketa: "Marketa",
  quill: "Quill",
  kn0w1: "Kn0w1",
  "aigent-z": "Aigent Z",
  "aigent-c": "Aigent C",
  "aigent-nakamoto": "Aigent Nakamoto",
};

/**
 * "Complete" semantics — either:
 *   - the operator manually marked the pill complete, OR
 *   - every artifact attached to the pill has been sent/published
 *     (with at least one artifact present so a queued-but-empty pill
 *     doesn't immediately read as complete).
 */
function isPillComplete(
  queued: ExpandedNBEPillQueuedState,
  artifacts: ArtifactCardData[],
): boolean {
  if (queued.manuallyComplete) return true;
  if (artifacts.length === 0) return false;
  return artifacts.every((a) => a.status === "sent" || a.status === "published");
}

/**
 * Of the suggested artifacts on a specialist response, pick the one
 * most likely to actually trigger a second-tier approval (i.e. the
 * one that externalises). Used by the "Approval required to implement →"
 * pill to drive a one-click draft + approve flow instead of just
 * scrolling.
 */
function pickApprovalArtifact(suggested: string[] | undefined): string | null {
  if (!suggested || suggested.length === 0) return null;
  const externalisingPriority = [
    "gmail-draft",
    "calendar-block",
    "calendar-invite",
    "post-set",
    "market-campaign",
  ];
  for (const candidate of externalisingPriority) {
    if (suggested.includes(candidate)) return candidate;
  }
  return suggested[0] ?? null;
}

export function ExpandedNBEPill({
  action,
  queued,
  specialistResponse,
  specialistLoading,
  specialistError,
  artifacts,
  secondTierApproval,
  using,
  actionPendingArtifactId,
  actionErrors,
  onDismissQueued,
  onDismissSpecialist,
  onUseSuggestedArtifact,
  onSendArtifact,
  onDismissArtifact,
  onApproveSecondTier,
  onCancelSecondTier,
  onMarkComplete,
  theme = "dark",
}: Props) {
  const isDark = theme === "dark";
  const complete = isPillComplete(queued, artifacts);

  // Border + accent tokens for queued (blue) vs complete (green).
  const borderClass = complete
    ? isDark
      ? "border-emerald-500/50 bg-emerald-500/[0.04]"
      : "border-emerald-400 bg-emerald-50/60"
    : isDark
      ? "border-sky-500/50 bg-sky-500/[0.04]"
      : "border-sky-400 bg-sky-50/60";

  const headerAccent = complete
    ? isDark ? "text-emerald-200" : "text-emerald-800"
    : isDark ? "text-sky-200" : "text-sky-800";

  const mutedClass = isDark ? "text-slate-400" : "text-slate-600";
  const stateLabel = complete ? "Complete" : "Queued";
  const StateIcon = complete ? CheckCircle2 : Check;

  // "Approval required to implement →" pill behaviour. Three branches:
  //  1) A second-tier approval is already open for an artifact in this
  //     pill → just scroll to it (avoid re-dispatching).
  //  2) An artifact is already drafted but no approval surfaced yet →
  //     scroll to that artifact so the operator can click its own
  //     Send/Approve control.
  //  3) Nothing drafted yet AND the specialist has suggested artifacts
  //     → auto-draft the most likely externalising one. The dispatcher
  //     opens the second-tier approval inline if the connector
  //     requires it, so the operator gets one-click "draft + approve"
  //     instead of the old "click → scroll → hunt for chip → click chip
  //     → wait → find approval somewhere else" loop.
  const handleRequestApproval = () => {
    if (secondTierApproval) {
      const target = artifacts.find((a) => a.artifactId === secondTierApproval.artifactId);
      if (target) {
        document
          .querySelector(`[data-artifact-id="${target.artifactId}"]`)
          ?.scrollIntoView({ behavior: "smooth", block: "start" });
        return;
      }
    }
    if (artifacts.length > 0) {
      document
        .querySelector(`[data-artifact-id="${artifacts[0].artifactId}"]`)
        ?.scrollIntoView({ behavior: "smooth", block: "start" });
      return;
    }
    if (specialistResponse && onUseSuggestedArtifact) {
      const artifactType = pickApprovalArtifact(specialistResponse.suggestedArtifacts);
      if (artifactType) {
        onUseSuggestedArtifact(artifactType, specialistResponse);
        return;
      }
    }
    // Last resort — surface the suggested-artifact chips so the
    // operator can pick one manually.
    document
      .querySelector(`[data-pill-intent-id="${queued.intentId}"] [data-suggested-artifacts]`)
      ?.scrollIntoView({ behavior: "smooth", block: "center" });
  };

  return (
    <div
      className={`rounded-xl border ${borderClass} p-3 space-y-3`}
      data-pill-intent-id={queued.intentId}
      data-pill-nbe-id={action.id}
      data-pill-state={complete ? "complete" : "queued"}
    >
      {/* Pill header — compresses the queued state + dismiss into one row */}
      <div className="flex items-start justify-between gap-3">
        <div className="flex-1 min-w-0">
          <div className={`flex items-center gap-2 text-xs uppercase tracking-wider mb-0.5 ${headerAccent}`}>
            <StateIcon className="w-3.5 h-3.5" />
            <span className="font-medium">{stateLabel}</span>
            <span className={mutedClass}>·</span>
            <span className={mutedClass}>
              {CARTRIDGE_LABELS[action.cartridge] ?? action.cartridge}
            </span>
            {action.specialist && (
              <>
                <span className={mutedClass}>·</span>
                <Users className={`w-3 h-3 ${mutedClass}`} />
                <span className={mutedClass}>
                  {SPECIALIST_LABELS[action.specialist] ?? action.specialist}
                </span>
              </>
            )}
          </div>
          <h4 className={`text-base font-semibold leading-tight ${isDark ? "text-slate-100" : "text-slate-900"}`}>
            {action.label}
          </h4>
          <p className={`text-sm mt-1 ${mutedClass}`}>{queued.queueMessage}</p>
          <p className={`text-[11px] mt-1.5 ${mutedClass}`}>
            intent: <span className="font-mono">{queued.intentId.slice(0, 8)}…</span>
            {" · status: "}
            <span className="font-mono">{complete ? "complete" : queued.status}</span>
          </p>
        </div>
        <div className="flex items-start gap-1 shrink-0">
          {!complete && onMarkComplete && (
            <button
              onClick={onMarkComplete}
              title="Mark this pill complete — flips to green"
              aria-label="Mark complete"
              className={`inline-flex items-center gap-1 px-2 py-1 rounded-md border text-[11px] font-medium transition ${
                isDark
                  ? "border-emerald-500/40 text-emerald-200 hover:bg-emerald-500/10"
                  : "border-emerald-400 text-emerald-700 hover:bg-emerald-50"
              }`}
            >
              <CheckSquare className="w-3 h-3" />
              Mark complete
            </button>
          )}
          <button
            onClick={onDismissQueued}
            className="p-1 rounded hover:bg-slate-800/40"
            aria-label="Dismiss"
          >
            <X className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Folded specialist response — recommendations + suggested artifact chips */}
      {(specialistResponse || specialistLoading || specialistError) && (
        <div data-suggested-artifacts>
          <SpecialistResponseCard
            data={specialistResponse ?? null}
            loading={specialistLoading}
            error={specialistError}
            using={using}
            onDismiss={onDismissSpecialist}
            onCreateArtifact={
              onUseSuggestedArtifact && specialistResponse
                ? (artifactType) => onUseSuggestedArtifact(artifactType, specialistResponse)
                : undefined
            }
            onRequestApproval={handleRequestApproval}
            theme={theme}
          />
        </div>
      )}

      {/* Specialist-not-yet-back inline loader (when no card is shown) */}
      {!specialistResponse && !specialistError && specialistLoading && (
        <div className={`text-xs flex items-center gap-2 ${mutedClass}`}>
          <Loader2 className="w-3 h-3 animate-spin" />
          Consulting specialist…
        </div>
      )}

      {/* Drafted artifact pills — each with optional second-tier approval */}
      {artifacts.map((artifact) => {
        const showSecondTier = secondTierApproval?.artifactId === artifact.artifactId;
        return (
          <div key={artifact.artifactId} data-artifact-id={artifact.artifactId} className="space-y-2">
            <ArtifactCard
              data={artifact}
              onAction={() => onSendArtifact(artifact.artifactId)}
              onDismiss={() => onDismissArtifact(artifact.artifactId)}
              actionPending={actionPendingArtifactId === artifact.artifactId}
              actionError={actionErrors?.[artifact.artifactId]}
              theme={theme}
            />
            {showSecondTier && secondTierApproval && onApproveSecondTier && onCancelSecondTier && (
              <SecondTierApprovalCard
                connectorLabel={secondTierApproval.connectorLabel}
                summary={secondTierApproval.summary}
                detail={secondTierApproval.detail}
                submitting={secondTierApproval.submitting}
                error={secondTierApproval.error}
                onApprove={onApproveSecondTier}
                onCancel={onCancelSecondTier}
                theme={theme}
              />
            )}
          </div>
        );
      })}

      {/* Footer state hint */}
      {complete && (
        <div className={`text-[11px] flex items-center gap-1.5 ${isDark ? "text-emerald-300/80" : "text-emerald-700"}`}>
          <Sparkles className="w-3 h-3" />
          All follow-on artifacts have shipped — this pill is complete.
        </div>
      )}
    </div>
  );
}

export default ExpandedNBEPill;
