-- OCSGA / Context Erosion research candidates for the CFS-051 Experiment /
-- Constitutional / Invariant Pipeline.
--
-- Provenance: exploratory RISE exchange with Ian McCoy (OCSGA) and the
-- OCSGA Constitutional Service Provider dossier:
--   docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md
--
-- IMPORTANT: these rows are CANDIDATES / HYPOTHESES. They are not ratified
-- experiments, not canonical invariants, and not claims about OCSGA's actual
-- implementation. Promotion remains governed by CFS-051 and the existing
-- formal EXPERIMENT_REGISTRY / invariant canon ceremonies.
--
-- Idempotent by slug so this migration can be safely replayed.

INSERT INTO public.research_candidate_experiments
  (slug, title, family, hypothesis, charter_ref, status, depends_on, source_note)
VALUES
  ('cand-exp-context-erosion-structural-invariance','Context Erosion as Structural Invariant Loss','Structural Invariance / Context Erosion','Context erosion can be operationalised as measurable loss of selected invariant properties across transformations of an information-bearing system, even while the surrounding representation legitimately changes.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed','{}','IRL hypothesis derived from Ian McCoy''s Context Erosion research. Candidate protocol: seed explicit structural invariants in a long-running workflow; apply summarisation, compression, retrieval, model swaps, tool accumulation and agent handoffs; measure semantic, constraint, provenance, objective and evidence fidelity after each transformation. Not Ian''s asserted definition.'),
  ('cand-exp-sovereign-state-anchoring','Sovereign-State Anchoring vs Context-Only Execution','Sovereign Runtime / Context Integrity','Keeping integrity-critical state in an external authoritative sovereign runtime will reduce invariant loss, authority drift and unrecoverable context failure compared with relying on mutable model context as the sole representation of state.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed',ARRAY['experiment:cand-exp-context-erosion-structural-invariance'],'Compare a context-only arm with a sovereign-state arm in which selected invariants are externally anchored and projected into execution context. Measure invariant fidelity, authority/mandate drift, recoverability, and execution errors.'),
  ('cand-exp-context-rehydration-recovery','Context Rehydration after Detected Erosion','Sovereign Runtime / Context Recovery','After detected context erosion, reconstructing bounded execution context from authoritative sovereign state will restore invariant fidelity more reliably than continuing from the compromised working context.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed',ARRAY['experiment:cand-exp-sovereign-state-anchoring'],'Controlled recovery experiment. Compare continued execution from degraded context against discard-and-rehydrate from authoritative state.'),
  ('cand-exp-invariant-custody-strategies','Preserved vs Anchored vs Derived Invariant Custody','Invariant Architecture / Sovereign Runtime','Different classes of invariants have different optimal custody strategies: some should be preserved through transformation, some anchored outside mutable context, and some derived or recomputed from authoritative state at execution time.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed',ARRAY['experiment:cand-exp-context-erosion-structural-invariance','experiment:cand-exp-sovereign-state-anchoring'],'Compare fidelity, latency, contradiction rate, cost and recoverability for candidate invariants stored in working context, externally anchored, or recomputed at runtime.'),
  ('cand-exp-authority-invariance-capability-scaling','Authority Invariance under Capability Scaling','Constitutionally Governed Autonomy','An increase in an agent''s capability, intelligence, autonomy or effectiveness shall not, by itself, increase the scope of its legitimate authority.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed','{}','Hold an authority/delegation envelope fixed while varying model capability, tools and autonomy.'),
  ('cand-exp-context-authority-propagation','Context Propagation without Authority Propagation','Multi-Agent Constitutional Invariance','Transferring context, instructions or task history between agents does not inherently transfer the originating actor''s authority or delegation.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed',ARRAY['experiment:cand-exp-authority-invariance-capability-scaling','experiment:cand-exp-context-erosion-structural-invariance'],'Multi-agent handoff experiment with and without independently valid authority/delegation evidence.'),
  ('cand-exp-consequence-aware-bounded-execution','Consequence-Aware Bounded Execution','Constitutionally Governed Autonomy / Consequence','Valid delegation is necessary but insufficient for legitimate autonomous execution: incorporating the current consequence envelope into the execution decision will reduce out-of-bounds consequential actions without requiring blanket human approval.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed',ARRAY['experiment:cand-exp-authority-invariance-capability-scaling'],'Hold mandate/delegation constant while varying prospective consequence, reversibility, affected parties and uncertainty.'),
  ('cand-exp-sovereign-runtime-ocsg-complementarity','Sovereign Runtime × OCSGA Complementarity','Constitutional Service Provider / Governed Execution','A sovereign state and intelligence runtime that anchors authoritative state can compose with a specialist governed-execution control plane without duplicating ownership of authority, runtime integrity or execution decisions.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed',ARRAY['experiment:cand-exp-sovereign-state-anchoring','experiment:cand-exp-consequence-aware-bounded-execution'],'Architecture hypothesis only until Ian McCoy''s OCSGA boundaries are mapped.'),
  ('cand-exp-authority-provenance-delegability','Authority Provenance and Delegability at Execution Mandate','Authority Provenance / Governed Execution','An execution-control system that verifies only the identity and intent of a delegating principal will accept mandates that should be rejected when the principal lacks the relevant authority or lacks the right to delegate it.','docs/dossiers/OCSGA_CONSTITUTIONAL_SERVICE_PROVIDER_DOSSIER.md','proposed',ARRAY['experiment:cand-exp-authority-invariance-capability-scaling'],'Construct matched mandates in which the human principal is authenticated and intentional, but vary whether the principal possesses the claimed authority and whether that authority is delegable. Evaluate mandate admission and execution decisions. This tests authority provenance independently of personhood or authentication.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.research_candidate_invariants
  (slug, namespace, statement, rationale, status, depends_on, source_note)
VALUES
  ('cand-inv-authority-invariant-capability','constitutional','Authority is invariant with respect to capability: no increase in an agent''s capability, intelligence, autonomy or effectiveness shall, by itself, increase the scope of its authority.','Capability describes what an actor can do; authority describes what it is legitimately entitled to do.','candidate',ARRAY['experiment:cand-exp-authority-invariance-capability-scaling'],'Candidate invariant emerging from the OCSGA / CI / IRL discussion.'),
  ('cand-inv-context-propagation-not-authority','constitutional','Context propagation does not imply authority propagation: receiving another actor''s context, instructions or task history does not itself transfer that actor''s authority or delegation.','Multi-agent systems can faithfully share context while still requiring independently valid authority provenance for consequential action.','candidate',ARRAY['experiment:cand-exp-context-authority-propagation'],'IRL candidate derived from the multi-agent Context Erosion / delegated-agency discussion.'),
  ('cand-inv-constitutional-depends-structural','constitutional','Constitutional invariance depends upon sufficient structural invariance of the state through which authority, mandate, delegation, evidence and consequence are interpreted.','A mandate cannot remain constitutionally reliable if its meaning, provenance or operative constraints have structurally eroded.','candidate',ARRAY['experiment:cand-exp-context-erosion-structural-invariance'],'IRL research proposition linking structural and constitutional layers.'),
  ('cand-inv-integrity-state-not-context-only','engineering','Integrity-critical authoritative state should not depend solely on mutable model working context when loss or drift of that state would invalidate evidence, mandate, authority or execution bounds.','External anchoring may allow mutable working context to evolve while authoritative state remains recoverable and re-projectable.','candidate',ARRAY['experiment:cand-exp-sovereign-state-anchoring','experiment:cand-exp-context-rehydration-recovery'],'Candidate engineering invariant for sovereign runtime research.'),
  ('cand-inv-delegation-no-ex-nihilo-authority','constitutional','Delegation cannot create authority ex nihilo: an actor may delegate only authority that it legitimately possesses and is entitled to delegate.','Personhood, authentication or intent alone does not establish authority over a domain. Every consequential delegation requires provenance to a legitimate authority source plus evidence that the authority is delegable.','candidate',ARRAY['experiment:cand-exp-authority-provenance-delegability'],'Candidate authority-provenance invariant. Applies human-to-human, human-to-agent, institution-to-human and agent sub-delegation chains.'),
  ('cand-inv-delegated-authority-bounded-upstream','constitutional','Delegated authority must be a subset of both the delegator''s legitimate authority and the portion of that authority that the delegator is permitted to delegate.','Holding authority to act and holding authority to delegate are distinct constitutional properties. Downstream authority cannot legitimately expand without an additional independent authority source.','candidate',ARRAY['experiment:cand-exp-authority-provenance-delegability'],'Working formalism: D(x→y) ⊆ A(x) ∩ G(x), where A is legitimate authority held and G is its delegable subset.'),
  ('cand-inv-personhood-not-sufficient-authority','constitutional','Constitutional personhood establishes the subject of authority but is not, by itself, sufficient evidence that the subject possesses authority to mandate a particular consequential act.','The person remains the constitutional unit, while authority over a specific domain may derive from personal sovereignty, consent, contract, role, ownership, institutional mandate, law or another legitimate source.','candidate',ARRAY['experiment:cand-exp-authority-provenance-delegability'],'Clarifies the boundary between Polity Passport personhood and authority credentials; candidate, not canon.'),
  ('cand-inv-execution-requires-authority-provenance','constitutional','Before consequential execution, the operative mandate must be traceable to sufficient authority provenance, including the current holder, source, scope, delegability, constraints, expiry or revocation state, and the delegation chain relevant to the proposed act.','Mandate inspection is the natural enforcement boundary because it connects credentialized upstream authority to the concrete act proposed for execution.','candidate',ARRAY['experiment:cand-exp-authority-provenance-delegability','experiment:cand-exp-consequence-aware-bounded-execution'],'Candidate enforcement invariant. OCSGA is a possible specialist execution-control layer, subject to architecture validation with Ian McCoy.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.research_backlog_items
  (slug, title, description, priority, status, linked_experiment_ids, linked_hypothesis_ids, source_note)
VALUES
  ('backlog-ocsg-context-erosion-gauntlet','Specify the Context Erosion / Invariant Integrity Gauntlet','Design one controlled long-running multi-agent workflow with 3-5 explicit invariants and staged transformations. Compare context-only baseline, sovereign-state anchoring, anchoring plus erosion detection and rehydration, and if OCSGA semantics support it after architecture review, anchoring plus governed execution.','high','backlog',ARRAY['cand-exp-context-erosion-structural-invariance','cand-exp-sovereign-state-anchoring','cand-exp-context-rehydration-recovery','cand-exp-context-authority-propagation','cand-exp-consequence-aware-bounded-execution'],ARRAY['cand-inv-authority-invariant-capability','cand-inv-context-propagation-not-authority','cand-inv-constitutional-depends-structural','cand-inv-integrity-state-not-context-only'],'Proposed as the first bounded joint IRL / OCSGA-compatible experiment.'),
  ('backlog-authority-credential-envelope','Specify the Authority Credential / Execution Mandate Envelope','Define and test a credentialized representation of authority associated with a constitutional subject: authority source, domain, scope, delegability, delegation depth, constraints, expiry, revocation, evidence and issuer. Determine whether this should extend the Polity Passport as linked authority credentials rather than overloading the proof-of-personhood credential itself. Define how an execution mandate references and proves the required authority chain at decision time.','high','backlog',ARRAY['cand-exp-authority-provenance-delegability','cand-exp-consequence-aware-bounded-execution'],ARRAY['cand-inv-delegation-no-ex-nihilo-authority','cand-inv-delegated-authority-bounded-upstream','cand-inv-personhood-not-sufficient-authority','cand-inv-execution-requires-authority-provenance'],'Architecture hypothesis: Passport anchors constitutional subject/personhood; separate linked verifiable authority credentials may express what authorities that subject holds. Enforcement is proposed at execution-mandate inspection. Exact credential model and OCSGA role require research before implementation.')
ON CONFLICT (slug) DO NOTHING;
