name: 'Build Check'

on:
  pull_request:
    branches: [ main, staging ]

jobs:
  build:
    name: 'Run Build Checks'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Cache node_modules (shared across branch commits)
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ github.head_ref || github.ref_name }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ github.head_ref || github.ref_name }}-

      # Step 4: Cache Next.js build (.next/cache) across branch commits
      - name: Cache Next.js Build
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: nextjs-cache-${{ github.head_ref || github.ref_name }}
          restore-keys: |
            nextjs-cache-${{ github.head_ref || github.ref_name }}-

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: |
          echo "Installing dependencies..."
          npm ci

      # Step 6: Build project
      - name: Build Project
        run: |
          echo "Building Next.js app..."
          npm run build
